spring:
  application:
    name: workflow-engine
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      connection-timeout: 60000
      maximum-pool-size: 100
      minimum-idle: 16
  jpa:
    show-sql: ${DB_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: jcache
        format_sql: ${DB_FORMAT_SQL:true}
    #        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
  cache:
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      config: classpath:ehcache.xml